name = "rps-backend"
main = "src/index.js"
compatibility_date = "2024-12-01"

[vars]
ALLOWED_ORIGINS = "https://rps.abhyasadh.com, http://localhost:5173"

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]
